image: ruby:2.4.2
stages:
  - build
  - test
  - review
  - stage
  - production

variables:
 DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
 - cd reddit
 - gem install bundler -v "=1.16"
 - bundle install
# - docker info
# - bundle update --bundler

build_job:
  image: docker:19.03.1-dind
  stage: build
  script:
    - echo 'Building'
    - cd ../docker-monolith
    - docker info
#    - apt update
#    - apt-cache search docker | grep docker
#    - apt install docker-ce
#    - docker build -t reddit:latest .
  tags:
   - dockerdind

test_unit_job:
 stage: test
 services:
 - mongo:latest
 script:
 - ruby simpletest.rb
# - echo 'test_unit_job'

deploy_dev_job:
 stage: review
 script:
  - echo 'Deploy'
 environment:
  name: dev
  url: http://dev.example.com

staging:
 stage: stage
 when: manual
 only:
  - /^\d+\.\d+\.\d+/
 script:
  - echo 'Deploy'
 environment:
  name: stage
  url: https://beta.example.com

production:
 stage: production
 when: manual
 only:
  - /^\d+\.\d+\.\d+/
 script:
  - echo 'Deploy'
 environment:
  name: production
  url: https://example.com
