image: ruby
stages:
  - build
  - test
  - review

variables:
 DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
 - cd reddit
# - gem install bundler -v "=1.16"
 - bundle install
# - bundle update --bundler

build_job:
  stage: build
  script:
    - echo 'Building'

test_unit_job:
 stage: test
 services:
 - mongo:latest
 script:
 - ruby simpletest.rb
# - echo 'test_unit_job'
 
deploy_dev_job:
 stage: review
 script:
  - echo 'Deploy'
 environment:
  name: dev
  url: http://dev.example.com
