dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    secure: a8sSOo1mWrsLXnX7xaDAD24mPkVBE1VBhcZ3yVHTKvY1s8vEn0iWEQqCczzxvFNYaurCR0L6UgVgFLv09zx5KC+BGKU/HChvbfqv5rcvHA1SVPjDqEEQRymnSW2DN3qmo2JeISXN5WkUq4deMPs4t51NfV9CP7M6VSMxhnoll3sld8nB4Jew5qps37CmbcN8pmlylIO7iFBq9LdT6aAGp3mfVqne53sCd2aeXzXjsUjVhQo6N1aGXWAw9u9Qp9dIKNl+WIkRB3UBhWwvooET85Sr6NjeYGCnFDf/Qn33/O09cADrzNFuf1cn5kJHqWWafVhjgXOKdl8dzyFI2g9rRC7dkVw+eLiZcm1kz1oqQUOc03xUu8tV3s28eBSgfCX7N/TcKzVE91lMJbWE3SVVYkc1jyzh2rNoIUopiftNRnGUoRSf+bYTRDBP3p4vCyQtYPiOQGS3TImWlOkj/1AMLnlqClDnJyuWK4fwHhAM82pFD6qyuJLDb4NdDzpiW9xDyTD7N7l5q7a+zhK/PD0eAV5NTb2lZzFrylzYIh4ZrAba3kWBbjSPeCAfqrmWk65uoCw2Ets1R6Kslrq9trpF6oQT12uXU8jHwvTq094AwZvibEG6E8fAC02EyDbZf4h0LLoDwEjb28DDQm3E9lnqG+XQ5DP1MLVTEPqH/PpPrBg=
