FROM alpine:3.7 AS builder

RUN apk add --update --no-cache ruby libressl \
    && apk add --no-cache --virtual .build-dependencies \
       build-base gcc musl-dev \
       ruby-dev \
       libressl-dev \
    && gem install --no-rdoc --no-ri bundler

ENV APP_HOME /app

RUN mkdir $APP_HOME

WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/

RUN bundle install \
    && apk del .build-dependencies \
    && rm -rf /usr/lib/ruby/gems/*/cache/* \
          /var/cache/apk/* \
          /tmp/* \
          /var/tmp/*

ADD . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
