global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#andrei_maiboroda'
