version: '3.3'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME1}/ui:${UI_VER}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME1}/post:${POST_VER}
    networks:
      - front_net
      - back_net

  comment:
    image: ${USERNAME1}/comment:${COMMENT_VER}
    networks:
      - front_net
      - back_net

  prometheus:
    image: ${USERNAME1}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
