version: '3.3'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME1}/ui:${UI_VER}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net
      - prometheus_net

  post:
    image: ${USERNAME1}/post:${POST_VER}
    networks:
      - front_net
      - back_net
      - prometheus_net

  comment:
    image: ${USERNAME1}/comment:${COMMENT_VER}
    networks:
      - front_net
      - back_net
      - prometheus_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
  prometheus_net:
