version: "3.3"

services:
 ui:
   command: puma --debug -w 2
   volumes:
    - ui_app:/app

 post:
   volumes:
    - post_app:/app

 comment:
   volumes:
    - comment_app:/app

volumes:
 ui_app:
 comment_app:
 post_app:
